Repository syndesisio/syndesis-react, pull requests merged in 2019-02, with the labels that each got.

#61 feat(checkbox): add support for basic pf3 checkbox
  packages/auto-form/.storybook/config.js
  packages/auto-form/package.json
  packages/auto-form/src/FormBuilder.tsx
  packages/auto-form/src/widgets/FormCheckboxComponent.tsx
  packages/auto-form/tests/AutoForm.spec.tsx
  yarn.lock
Labels: approved, enhancement, status/review-requested

#63 Fix Storybook build errors
  packages/ui/package.json
  packages/ui/stories/Connection/ConnectionCard.stories.tsx
  packages/ui/stories/Connection/ConnectionsListView.stories.tsx
  packages/ui/stories/Layout/AppLayout.stories.tsx
  yarn.lock
Labels: approved, status/review-requested

#64 fix(storybook): unbreak storybook for ui pkg
  packages/ui/stories/Connection/ConnectionCard.stories.tsx
  packages/ui/stories/Layout/AppLayout.stories.tsx
Labels: approved, bug, status/review-requested

#66 feat(textarea): add pf3 textarea and storybook
  packages/auto-form/src/widgets/FormTextAreaComponent.tsx
  packages/auto-form/stories/FormTextAreaComponent.stories.tsx
Labels: approved, enhancement, status/review-requested

#65 feat(checkbox): add support for disabled state and storybook
  packages/auto-form/package.json
  packages/auto-form/src/widgets/FormCheckboxComponent.tsx
  packages/auto-form/stories/FormCheckboxComponent.stories.tsx
  yarn.lock
Labels: approved, enhancement, status/review-requested

#67 chore(form-controls): more test coverage and types for formcontrols
  packages/auto-form/src/models.ts
  packages/auto-form/src/widgets/FormCheckboxComponent.tsx
  packages/auto-form/src/widgets/FormTextAreaComponent.tsx
  packages/auto-form/stories/FormCheckboxComponent.stories.tsx
  packages/auto-form/stories/FormTextAreaComponent.stories.tsx
  packages/auto-form/tests/FormCheckboxComponent.spec.tsx
  packages/auto-form/tests/FormTextAreaComponent.spec.tsx
Labels: approved, status/review-requested

#68 feat(textinput): add support for pf3 text input control
  packages/auto-form/src/models.ts
  packages/auto-form/src/widgets/FormInputComponent.tsx
  packages/auto-form/stories/FormCheckboxComponent.stories.tsx
  packages/auto-form/stories/FormInputComponent.stories.tsx
  packages/auto-form/stories/FormTextAreaComponent.stories.tsx
  packages/auto-form/tests/FormInputComponent.spec.tsx
Labels: approved, enhancement, status/review-requested

#69 feat(select): use pf3 FormControl for select component
  packages/auto-form/src/widgets/FormCheckboxComponent.tsx
  packages/auto-form/src/widgets/FormSelectComponent.tsx
  packages/auto-form/stories/FormSelectComponent.stories.tsx
  packages/auto-form/tests/FormSelectComponent.spec.tsx
Labels: approved, enhancement, status/review-requested

#60 ttools-565 - initial virtualization item and list view components and…
  packages/ui/src/Data/Virtualizations/VirtListItem.tsx
  packages/ui/src/Data/Virtualizations/VirtListView.tsx
  packages/ui/src/Data/index.ts
  packages/ui/src/index.ts
  packages/ui/stories/Data/Virtualizations/VirtListItem.stories.tsx
  packages/ui/stories/Data/Virtualizations/VirtListView.stories.tsx
Labels: approved, status/review-requested

#73 TEIIDTOOLS-567
  packages/api/src/ApiContext.tsx
  packages/api/src/DVFetch.tsx
  packages/api/src/WithVirtualizations.tsx
  packages/api/src/callDVFetch.ts
  packages/api/src/index.ts
  packages/models/src/dv.d.ts
  packages/models/src/index.d.ts
  packages/ui/src/Data/Virtualizations/VirtListSkeleton.tsx
  packages/ui/src/Data/Virtualizations/VirtListView.tsx
  packages/ui/src/Data/index.ts
  syndesis/config.json.minishift
  syndesis/src/app/App.tsx
  syndesis/src/app/WithConfig.tsx
  syndesis/src/app/__mocks__/WithConfig.tsx
  syndesis/src/i18n/index.ts
  syndesis/src/i18n/locales/index.ts
  syndesis/src/i18n/locales/shared-translations.en.json
  syndesis/src/i18n/locales/shared-translations.it.json
  syndesis/src/index.tsx
  syndesis/src/modules/data/DataApp.tsx
  syndesis/src/modules/data/index.tsx
  syndesis/src/modules/data/locales/data-translations.en.json
  syndesis/src/modules/data/locales/data-translations.it.json
  syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  syndesis/src/modules/index.ts
Labels: approved, status/review-requested

#76 TEIIDTOOLS-569 Addition of ViewList and stories
  packages/api/src/callDVFetch.ts
  packages/api/src/index.ts
  packages/ui/src/Data/Views/ViewListItem.tsx
  packages/ui/src/Data/Views/ViewListSkeleton.tsx
  packages/ui/src/Data/Views/ViewListView.tsx
  packages/ui/src/Data/Virtualizations/VirtListItem.tsx
  packages/ui/src/Data/Virtualizations/VirtListView.tsx
  packages/ui/src/Data/index.ts
  packages/ui/stories/Data/Views/ViewListItem.stories.tsx
  packages/ui/stories/Data/Views/ViewListView.stories.tsx
Labels: approved, status/review-requested

#62 feat(integrationDetailHistoryListViewItem)
  packages/ui/src/Integration/IntegrationDetailHistoryListViewItem.tsx
  packages/ui/src/Integration/index.ts
  packages/ui/stories/Integration/IntegrationActivityTab.stories.tsx
  packages/ui/stories/Integration/IntegrationDetailHistoryListViewItem.stories.tsx
Labels: approved

#81 TEIIDTOOLS-583 Update routing for DV pages
  packages/ui/src/Data/Virtualizations/VirtListItem.tsx
  packages/ui/stories/Data/Views/ViewListView.stories.tsx
  packages/ui/stories/Data/Virtualizations/VirtListItem.stories.tsx
  packages/ui/stories/Data/Virtualizations/VirtListView.stories.tsx
  syndesis/src/modules/data/DataApp.tsx
  syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
  syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  syndesis/src/modules/data/resolvers.ts
  syndesis/src/modules/data/routes.ts
Labels: approved, status/review-requested

#74 feat: upgrade the connections module to use the routes/resolvers pattern.
  packages/utils/package.json
  packages/utils/src/index.ts
  packages/utils/src/makeResolver.ts
  syndesis/src/modules/connections/ConnectionsApp.tsx
  syndesis/src/modules/connections/containers/ConnectionsWithToolbar.tsx
  syndesis/src/modules/connections/index.tsx
  syndesis/src/modules/connections/pages/ConnectionsPage.tsx
  syndesis/src/modules/connections/pages/ConnectorFormPage.tsx
  syndesis/src/modules/connections/pages/ConnectorsPage.tsx
  syndesis/src/modules/connections/resolvers.ts
  syndesis/src/modules/connections/routes.ts
  syndesis/src/modules/dashboard/pages/DashboardPage.tsx
  syndesis/src/modules/integrations/resolvers.ts
  syndesis/src/modules/resolvers.ts
  yarn.lock
Labels: status/review-requested

#80 feature(integrationDetailHistoryListView)
  packages/ui/src/Integration/IntegrationDetailHistoryListView.tsx
  packages/ui/src/Integration/IntegrationDetailHistoryListViewItem.tsx
  packages/ui/src/Integration/index.ts
  packages/ui/stories/Integration/IntegrationDetailHistoryListView.stories.tsx
  packages/ui/stories/Integration/IntegrationDetailHistoryListViewItem.stories.tsx
Labels: approved, status/review-requested
