Repository syndesisio/syndesis-react, pull requests merged in 2019-03, with the labels that each got.

#85 bugfix(autoform): properly handle required fields
  packages/auto-form/src/AutoForm.tsx
  packages/auto-form/src/FormBuilder.tsx
  packages/auto-form/src/models.ts
  packages/auto-form/src/widgets/FormCheckboxComponent.tsx
  packages/auto-form/src/widgets/FormHiddenComponent.tsx
  packages/auto-form/src/widgets/FormInputComponent.tsx
  packages/auto-form/src/widgets/FormSelectComponent.tsx
  packages/auto-form/src/widgets/FormTextAreaComponent.tsx
  packages/auto-form/src/widgets/helpers.ts
  packages/auto-form/tests/AutoForm.spec.tsx
  packages/auto-form/tests/FormCheckboxComponent.spec.tsx
  packages/auto-form/tests/FormInputComponent.spec.tsx
  packages/auto-form/tests/FormSelectComponent.spec.tsx
  packages/auto-form/tests/FormTextAreaComponent.spec.tsx
  packages/models/src/extra.d.ts
Labels: approved, status/review-requested

#87 Implements Extension Delete Functionality
  packages/api/src/WithExtensionHelpers.tsx
  packages/api/src/callFetch.ts
  packages/api/src/index.ts
  packages/ui/src/Customization/ExtensionDetail.tsx
  packages/ui/src/Customization/ExtensionListItem.tsx
  packages/ui/src/Shared/DeleteConfirmationDialog.tsx
  packages/ui/src/Shared/index.ts
  packages/ui/stories/Customization/ExtensionDetail.stories.tsx
  packages/ui/stories/Customization/ExtensionListItem.stories.tsx
  packages/ui/stories/Customization/ExtensionListView.stories.tsx
  packages/ui/stories/Shared/DeleteConfirmationDialog.stories.tsx
  syndesis/src/modules/customizations/locales/customizations-translations.en.json
  syndesis/src/modules/customizations/locales/customizations-translations.it.json
  syndesis/src/modules/customizations/pages/ExtensionDetailsPage.tsx
  syndesis/src/modules/customizations/pages/ExtensionsPage.tsx
Labels: approved

#90 TTOOLS-587 Implement delete virtualization
  packages/api/src/WithVirtualizationHelpers.tsx
  packages/api/src/index.ts
  packages/ui/src/Data/Virtualizations/VirtListItem.tsx
  packages/ui/stories/Data/Virtualizations/VirtListItem.stories.tsx
  packages/ui/stories/Data/Virtualizations/VirtListView.stories.tsx
  syndesis/src/modules/data/locales/data-translations.en.json
  syndesis/src/modules/data/locales/data-translations.it.json
  syndesis/src/modules/data/pages/VirtualizationsPage.tsx
Labels: approved, status/review-requested

#93 TTOOLS-570 Add children to virtualization item to allow expanding vie…
  packages/ui/src/Data/Virtualizations/VirtListItem.tsx
  packages/ui/stories/Data/Virtualizations/VirtListView.stories.tsx
Labels: approved, status/review-requested

#97 TTOOLS-588 Adds CreateVirtualization
  packages/api/src/WithVirtualizationHelpers.tsx
  packages/ui/src/Data/Virtualizations/VirtListView.tsx
  packages/ui/stories/Data/Virtualizations/VirtListView.stories.tsx
  syndesis/src/i18n/locales/shared-translations.en.json
  syndesis/src/i18n/locales/shared-translations.it.json
  syndesis/src/modules/data/locales/data-translations.en.json
  syndesis/src/modules/data/locales/data-translations.it.json
  syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
  syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  syndesis/src/modules/resolvers.ts
Labels: approved, status/review-requested

#98 fix storybook build issue
  packages/ui/stories/Data/Virtualizations/VirtListView.stories.tsx
Labels: status/review-requested

#99 Refactor 'virt' to 'virtualization'
  packages/ui/src/Data/Views/ViewList.tsx
  packages/ui/src/Data/Virtualizations/VirtualizationList.tsx
  packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  packages/ui/src/Data/Virtualizations/VirtualizationListSkeleton.tsx
  packages/ui/src/Data/index.ts
  packages/ui/stories/Data/Views/ViewList.stories.tsx
  packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  syndesis/src/modules/data/pages/VirtualizationsPage.tsx
Labels: approved, status/review-requested

#100 Fixes Lint error.
  syndesis/src/modules/data/pages/VirtualizationsPage.tsx
Labels: approved, status/review-requested

#101 TTOOLS-593 Now utilizing virtualization publish status
  packages/models/src/dv.d.ts
  packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  packages/ui/src/Data/Virtualizations/VirtualizationPublishStatus.tsx
  packages/ui/src/Data/Virtualizations/VirtualizationPublishStatusDetail.tsx
  packages/ui/src/Data/Virtualizations/models.ts
  packages/ui/src/Data/index.ts
  packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  packages/ui/stories/Data/Virtualizations/VirtualizationPublishStatus.stories.tsx
  packages/ui/stories/Data/Virtualizations/VirtualizationPublishStatusDetail.stories.tsx
  syndesis/src/modules/data/locales/data-translations.en.json
  syndesis/src/modules/data/locales/data-translations.it.json
  syndesis/src/modules/data/pages/VirtualizationsPage.tsx
Labels: approved, status/review-requested

#103 fix(readme): correct broken links, improve getting started steps
  README.md
  packages/auto-form/yalc.lock
Labels: approved

#105 Rm yalc.lock
  packages/auto-form/yalc.lock
Labels: approved

#102 TTOOLS-593 Adds publish - unpublish virtualization
  packages/api/src/WithVirtualizationHelpers.tsx
  packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  syndesis/src/modules/data/pages/VirtualizationsPage.tsx
Labels: approved, status/review-requested

#108 Add Customizations Extensions Page stories
  packages/ui/stories/Customization/ExtensionDetail.stories.tsx
  packages/ui/stories/Customization/ExtensionImport.stories.tsx
  packages/ui/stories/Customization/ExtensionListItem.stories.tsx
  packages/ui/stories/Customization/ExtensionListView.stories.tsx
  packages/ui/stories/Customization/ExtensionsPage.stories.tsx
  syndesis/src/modules/customizations/pages/ExtensionsPage.tsx
Labels: status/review-requested

#109 Implementation of Extension Import
  packages/.storybook/config.js
  packages/api/src/WithExtensionHelpers.tsx
  packages/api/src/callFetch.ts
  packages/ui/package.json
  packages/ui/src/Customization/ApiConnectorDetailCard.tsx
  packages/ui/src/Customization/ApiConnectorListItem.tsx
  packages/ui/src/Customization/ExtensionImport.tsx
  packages/ui/src/Customization/ExtensionImportCard.tsx
  packages/ui/src/Customization/ExtensionImportReview.css
  packages/ui/src/Customization/ExtensionImportReview.tsx
  packages/ui/src/Customization/ExtensionListItem.tsx
  packages/ui/src/Customization/index.ts
  packages/ui/src/Layout/ButtonLink.tsx
  packages/ui/src/Shared/DndFileChooser.css
  packages/ui/src/Shared/DndFileChooser.tsx
  packages/ui/src/Shared/index.ts
  packages/ui/stories/Customization/ApiConnectorDetail.stories.tsx
  packages/ui/stories/Customization/ApiConnectorListItem.stories.tsx
  packages/ui/stories/Customization/ApiConnectorListView.stories.tsx
  packages/ui/stories/Customization/ExtensionDetail.stories.tsx
  packages/ui/stories/Customization/ExtensionImport.stories.tsx
  packages/ui/stories/Customization/ExtensionImportCard.stories.tsx
  packages/ui/stories/Customization/ExtensionImportReview.stories.tsx
  packages/ui/stories/Customization/ExtensionListItem.stories.tsx
  packages/ui/stories/Customization/ExtensionListView.stories.tsx
  packages/ui/stories/Shared/DeleteConfirmationDialog.stories.tsx
  packages/ui/stories/Shared/DndFileChooser.stories.tsx
  packages/ui/tests/Customization/ExtensionImportReview.spec.tsx
  syndesis/src/i18n/locales/shared-translations.en.json
  syndesis/src/i18n/locales/shared-translations.it.json
  syndesis/src/modules/customizations/CustomizationsApp.tsx
  syndesis/src/modules/customizations/customizationsUtils.ts
  syndesis/src/modules/customizations/locales/customizations-translations.en.json
  syndesis/src/modules/customizations/locales/customizations-translations.it.json
  syndesis/src/modules/customizations/pages/ExtensionImportPage.css
  syndesis/src/modules/customizations/pages/ExtensionImportPage.tsx
  syndesis/src/modules/customizations/pages/ExtensionsPage.tsx
  syndesis/src/modules/customizations/resolvers.ts
  yarn.lock
Labels: approved, status/review-requested

#110 Fix for Virtualization list EmptyState
  packages/ui/src/Data/Views/ViewList.tsx
  packages/ui/src/Data/Virtualizations/VirtualizationList.tsx
  packages/ui/stories/Data/Views/ViewList.stories.tsx
  packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  syndesis/src/modules/data/pages/VirtualizationsPage.tsx
Labels: approved, status/review-requested
