Repository syndesisio/syndesis-react, pull requests merged in 2019-05, with the labels that each got.

#209 chore: editor placeholder pages
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/ui/src/Integration/IntegrationEditorChooseAction.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/api-provider/EditPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/api-provider/ReviewPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/api-provider/UploadPage.tsx
  app/ui-react/syndesis/src/modules/integrations/index.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/IntegrationsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/resolvers.ts
  app/ui-react/syndesis/src/modules/integrations/routes.ts
Labels: approved, status/review-requested

#214 bugfix: don't crash editing an integration with steps other than endpoints
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/api/tests/helpers/integrationFunctions.spec.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailSteps.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
  app/ui-react/syndesis/src/modules/integrations/resolvers.ts
Labels: approved, status/review-requested

#212 Breadcrumbs and other things..
  app/ui-react/packages/ui/src/Integration/IntegrationDetailBreadcrumb.css
  app/ui-react/packages/ui/src/Integration/IntegrationDetailBreadcrumb.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationDetailHistoryListView.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationDetailHistoryListViewItemActions.tsx
  app/ui-react/packages/ui/src/Integration/index.ts
  app/ui-react/packages/ui/src/Shared/index.ts
  app/ui-react/packages/ui/src/Shared/models.ts
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailHistory.tsx
  app/ui-react/syndesis/src/modules/integrations/components/index.ts
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx
Labels: approved, status/review-requested

#219 chore: refactor integration actions into it's own component
  app/ui-react/packages/api/src/WithIntegration.tsx
  app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx
  app/ui-react/syndesis/src/modules/integrations/components/WithIntegrationActions.tsx
  app/ui-react/syndesis/src/modules/integrations/components/index.ts
  app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx
Labels: approved, status/review-requested

#205 feat(about-modal): add help dropdown and about modal
  app/ui-react/packages/api/src/SyndesisFetch.tsx
  app/ui-react/packages/api/src/WithApiVersion.tsx
  app/ui-react/packages/api/src/callFetch.ts
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/models/src/extra.d.ts
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/Layout/AppLayout.tsx
  app/ui-react/packages/ui/src/Shared/AboutModal.tsx
  app/ui-react/packages/ui/src/Shared/AboutModalContent.tsx
  app/ui-react/packages/ui/src/Shared/HelpDropdown.tsx
  app/ui-react/packages/ui/src/Shared/index.ts
  app/ui-react/packages/ui/src/index.css
  app/ui-react/packages/ui/stories/Layout/AppLayout.stories.tsx
  app/ui-react/packages/ui/stories/Shared/AboutModal.stories.tsx
  app/ui-react/packages/ui/stories/Shared/HelpDropdown.stories.tsx
  app/ui-react/packages/ui/tests/AppLayout.spec.tsx
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/shared/images/pf4-downstream-bg.svg
  app/ui-react/syndesis/src/shared/images/redhat-favicon.svg
  app/ui-react/syndesis/src/shared/images/syndesis-logo-graphic.png
  app/ui-react/yarn.lock
Labels: approved, status/review-requested

#220 feat: Flesh out the detail page a bit more
  app/ui-react/packages/api/src/WithActivities.tsx
  app/ui-react/packages/api/src/WithMonitoredIntegration.tsx
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/models/src/extra.d.ts
  app/ui-react/packages/ui/src/Integration/IntegrationDetailInfo.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailHeader.tsx
  app/ui-react/syndesis/src/modules/integrations/components/index.ts
  app/ui-react/syndesis/src/modules/integrations/pages/detail/ActivityPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/ActivityPageTable.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/MetricsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/index.ts
Labels: approved

#215 Integration Detail: Metrics tab
  app/ui-react/packages/api/src/WithIntegrationMetrics.tsx
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/ui/src/Integration/IntegrationDetailMetrics.tsx
  app/ui-react/packages/ui/stories/Integration/IntegrationDetail.stories.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/MetricsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/resolvers.ts
  app/ui-react/syndesis/src/modules/integrations/shared/IntegrationDetailNavBar.tsx
Labels: approved

#224 Docker image build and push from CI
  .circleci/config.yml
  app/ui-react/.dockerignore
  app/ui-react/Dockerfile
  app/ui-react/nginx-syndesis.conf
  app/ui-react/nginx.repo
  install/generator/02-syndesis-image-streams.yml.mustache
  install/syndesis.yml
Labels: approved, status/review-requested

#226 fix: CircleCI `publish` operates in `~`
  .circleci/config.yml
Labels: approved, status/review-requested

#227 fix: CircleCI `publish` operates in `~/project`
  .circleci/config.yml
Labels: approved, status/review-requested

#229 fix: fix: CircleCI `publish` image/tag for push
  .circleci/config.yml
Labels: approved, status/review-requested

#231 fix: `deploy` command `image` parameter ident
  .circleci/config.yml
Labels: approved

#232 refactor: ci docker build publish
  .circleci/config.yml
Labels: approved

#233 fix: ci docker publish, specify Dockerfile path
  .circleci/config.yml
Labels: approved

#234 feat: finish up detail pages, connect things, align things, show proper duration values
  app/ui-react/packages/api/src/WithIntegrationHelpers.tsx
  app/ui-react/packages/ui/src/Dashboard/UptimeMetric.tsx
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.css
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationBulletinBoardAlert.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailDescription.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailEditableName.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.tsx
  app/ui-react/packages/ui/src/Integration/Details/index.ts
  app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
  app/ui-react/packages/ui/stories/Integration/IntegrationDetail.stories.tsx
  app/ui-react/packages/utils/package.json
  app/ui-react/packages/utils/src/dateHelpers.ts
  app/ui-react/packages/utils/src/index.ts
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailHeader.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/ActivityPageTable.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/MetricsPage.tsx
  app/ui-react/yarn.lock
Labels: approved

#235 chore: use pf4 headers for the editor
  app/ui-react/packages/ui/src/Integration/IntegrationEditorChooseAction.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationEditorChooseConnection.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationEditorForm.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationEditorLayout.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationEditorNothingToConfigure.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationSaveForm.tsx
  app/ui-react/packages/ui/src/Integration/index.ts
  app/ui-react/packages/ui/src/index.css
  app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/SelectActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/shared/WithConfigurationForm.tsx
Labels: approved, status/review-requested

#236 fix: dedupe bulletin board messages and combine details as needed
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailHeader.tsx
Labels: approved

#237 chore: update dependencies to the latest versions
  .circleci/config.yml
  app/ui-react/package.json
  app/ui-react/packages/api/package.json
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/api/tests/Fetch.spec.tsx
  app/ui-react/packages/api/tests/helpers/integrationFunctions.spec.tsx
  app/ui-react/packages/atlasmap-adapter/package.json
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/packages/auto-form/package.json
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/Integration/IntegrationFlowStepDetails.tsx
  app/ui-react/packages/ui/tests/Customization/ExtensionDetail.spec.tsx
  app/ui-react/packages/ui/tests/Customization/ExtensionListItem.spec.tsx
  app/ui-react/packages/utils/package.json
  app/ui-react/syndesis/.env
  app/ui-react/syndesis/package.json
  app/ui-react/syndesis/src/modules/data/shared/HeaderView.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewSqlForm.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewSqlFormAndTable.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorSidebar.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
  app/ui-react/syndesis/src/modules/integrations/components/Integrations.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/IntegrationsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/shared/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/shared/WithClosedNavigation.tsx
  app/ui-react/yarn.lock
Labels: approved

#241 TTOOLS-609 Refactor SqlClient page
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientForm.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/EmptyViewsState.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/EmptyViewsState.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewHeader.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewList.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewList.tsx
  app/ui-react/packages/ui/src/Data/index.ts
  app/ui-react/packages/ui/stories/Data/Views/EmptyViewsState.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewHeader.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/SqlClientContent.stories.tsx
  app/ui-react/packages/ui/stories/Shared/GenericTable.stories.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationMetricsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationRelationshipPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationSqlClientPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/HeaderView.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewSqlForm.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewSqlFormAndTable.tsx
  app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
  app/ui-react/syndesis/src/modules/data/shared/index.ts
Labels: approved, status/review-requested

#239 chore: overall layout cleanup
  app/ui-react/packages/ui/src/Connection/ConnectionsListView.tsx
  app/ui-react/packages/ui/src/Customization/ApiConnectorListView.tsx
  app/ui-react/packages/ui/src/Customization/ExtensionListView.tsx
  app/ui-react/packages/ui/src/Dashboard/Dashboard.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationList.tsx
  app/ui-react/packages/ui/src/Integration/CiCd/CiCdListView.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationEditorChooseAction.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationEditorChooseConnection.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationEditorForm.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationEditorLayout.css
  app/ui-react/packages/ui/src/Integration/IntegrationEditorLayout.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationEditorNothingToConfigure.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationSaveForm.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationVerticalFlow.css
  app/ui-react/packages/ui/src/Integration/IntegrationVerticalFlow.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsListView.tsx
  app/ui-react/packages/ui/src/Integration/index.ts
  app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppListItemView.tsx
  app/ui-react/packages/ui/src/Shared/InlineTextEdit.tsx
  app/ui-react/packages/ui/src/Shared/SimplePageHeader.tsx
  app/ui-react/packages/ui/src/index.css
  app/ui-react/packages/ui/stories/Connection/ConnectionsListView.stories.tsx
  app/ui-react/packages/ui/tests/ConnectionsListView.test.tsx
  app/ui-react/syndesis/src/i18n/index.ts
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.it.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/connections/components/Connections.tsx
  app/ui-react/syndesis/src/modules/connections/components/ConnectionsWithToolbar.tsx
  app/ui-react/syndesis/src/modules/connections/locales/connections-translations.en.json
  app/ui-react/syndesis/src/modules/connections/pages/ConnectionsPage.tsx
  app/ui-react/syndesis/src/modules/dashboard/index.tsx
  app/ui-react/syndesis/src/modules/dashboard/locales/dashboard-translations.en.json
  app/ui-react/syndesis/src/modules/dashboard/locales/dashboard-translations.it.json
  app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorSidebar.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/SelectActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/pages/IntegrationsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/resolvers.ts
  app/ui-react/syndesis/src/modules/integrations/shared/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/shared/WithClosedNavigation.tsx
Labels: approved, status/review-requested

#244 fix: dump the grid for the horizontal flow view, add links/tooltips to connections
  app/ui-react/packages/api/src/helpers/connectionFunctions.ts
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivity.css
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivity.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationFlowStepDetails.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationFlowStepWithOverview.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationStepsHorizontalItem.css
  app/ui-react/packages/ui/src/Integration/IntegrationStepsHorizontalItem.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationStepsHorizontalView.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailSteps.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorSidebar.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: approved

#223 Connections Card Widget
  app/ui-react/packages/ui/src/Connection/ConnectionCard.css
  app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx
  app/ui-react/packages/ui/src/index.css
  app/ui-react/packages/ui/stories/Connection/ConnectionCard.stories.tsx
  app/ui-react/packages/ui/stories/Connection/ConnectionsListView.stories.tsx
  app/ui-react/packages/ui/tests/ConnectionCard.spec.tsx
  app/ui-react/syndesis/src/i18n/index.ts
  app/ui-react/syndesis/src/modules/connections/components/Connections.tsx
  app/ui-react/syndesis/src/modules/connections/locales/connections-translations.en.json
  app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.tsx
Labels: approved, status/review-requested

#245 feat(help-dropdown): add help dropdown entries
  app/ui-react/packages/ui/src/Layout/AppLayout.tsx
  app/ui-react/packages/ui/src/Shared/AboutModalContent.tsx
  app/ui-react/packages/ui/src/Shared/HelpDropdown.tsx
  app/ui-react/packages/ui/src/Shared/SimplePageHeader.tsx
  app/ui-react/packages/ui/src/Support/SupportPageBody.tsx
  app/ui-react/packages/ui/src/Support/index.ts
  app/ui-react/packages/ui/src/index.ts
  app/ui-react/packages/ui/stories/Layout/AppLayout.stories.tsx
  app/ui-react/packages/ui/stories/Shared/HelpDropdown.stories.tsx
  app/ui-react/packages/ui/tests/AppLayout.spec.tsx
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/index.tsx
  app/ui-react/syndesis/src/modules/index.ts
  app/ui-react/syndesis/src/modules/resolvers.ts
  app/ui-react/syndesis/src/modules/routes.ts
  app/ui-react/syndesis/src/modules/support/index.tsx
  app/ui-react/syndesis/src/modules/support/pages/SupportPage.tsx
  app/ui-react/syndesis/src/modules/support/resolvers.ts
  app/ui-react/syndesis/src/modules/support/routes.ts
Labels: approved, status/review-requested

#257 fix: small bugfixes to the IVP and the Add step page
  app/ui-react/packages/ui/src/Integration/IntegrationEditorStepsList.css
  app/ui-react/packages/ui/src/Integration/IntegrationEditorStepsList.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationEditorStepsListItem.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationFlowAddStep.css
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
Labels: approved

#258 feat: fetch the action descriptor up-front
  app/ui-react/packages/api/src/Fetch.tsx
  app/ui-react/packages/api/src/SyndesisFetch.tsx
  app/ui-react/packages/api/src/WithActionDescriptor.tsx
  app/ui-react/packages/api/src/WithIntegrationHelpers.tsx
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/ui/src/Integration/IntegrationEditorForm.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationEditorNothingToConfigure.tsx
  app/ui-react/packages/ui/src/Integration/editor/index.ts
  app/ui-react/packages/ui/src/Integration/editor/shared/PageSectionLoader.tsx
  app/ui-react/packages/ui/src/Integration/editor/shared/index.ts
  app/ui-react/packages/ui/src/Integration/index.ts
  app/ui-react/packages/utils/src/autoformHelpers.ts
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailSteps.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/shared/WithConfigurationForm.tsx
Labels: approved

#260 feat: add the step configuration page, plus the required helpers
  app/ui-react/packages/api/src/WithIntegrationHelpers.tsx
  app/ui-react/packages/api/src/WithOAuthApps.tsx
  app/ui-react/packages/api/src/WithSteps.tsx
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
  app/ui-react/packages/models/src/extra.d.ts
  app/ui-react/packages/ui/src/Integration/IntegrationEditorForm.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationEditorLayout.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationEditorNothingToConfigure.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailHeader.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailNavBar.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/step/ConfigureStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
  app/ui-react/syndesis/src/modules/integrations/resolvers.ts
  app/ui-react/syndesis/src/modules/integrations/shared/index.ts
Labels: approved, status/review-requested

#265 feat: add support for extensions
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: approved, status/review-requested

#264 feat: show a notification when a new version of the app is available
  app/ui-react/packages/ui/src/Layout/ButtonLink.tsx
  app/ui-react/packages/ui/src/Shared/DndFileChooser.tsx
  app/ui-react/packages/ui/src/Shared/Notifications.tsx
  app/ui-react/syndesis/package.json
  app/ui-react/syndesis/public/manifest.json
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/typings/workbox-window/index.d.ts
  app/ui-react/typings/workbox-window/package.json
Labels: approved, status/review-requested

#266 feat: wire in the template step page and get it saving/loading
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.tsx
  app/ui-react/packages/ui/src/Integration/editor/index.ts
  app/ui-react/packages/ui/src/Integration/editor/steps/index.ts
  app/ui-react/packages/ui/src/Integration/editor/steps/template/TemplateStepCard.tsx
  app/ui-react/packages/ui/src/Integration/editor/steps/template/TemplateStepTemplateEditor.tsx
  app/ui-react/packages/ui/src/Integration/editor/steps/template/TemplateStepTypeSelector.tsx
  app/ui-react/packages/ui/src/Integration/editor/steps/template/index.ts
  app/ui-react/packages/ui/src/Shared/TextEditor.tsx
  app/ui-react/packages/ui/src/Shared/index.ts
  app/ui-react/packages/ui/stories/Integration/editor/steps/TemplateStep.stories.tsx
  app/ui-react/packages/ui/stories/Shared/TextEditor.stories.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/TemplateStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/WithTemplater.tsx
  app/ui-react/syndesis/src/modules/integrations/resolvers.ts
  app/ui-react/yarn.lock
Labels: approved

#263 Home/Dashboard
  app/ui-react/packages/ui/src/Dashboard/ConnectionsMetric.css
  app/ui-react/packages/ui/src/Dashboard/ConnectionsMetric.tsx
  app/ui-react/packages/ui/src/Dashboard/Dashboard.css
  app/ui-react/packages/ui/src/Dashboard/Dashboard.tsx
  app/ui-react/packages/ui/src/Dashboard/RecentUpdatesItem.css
  app/ui-react/packages/ui/src/Dashboard/RecentUpdatesItem.tsx
  app/ui-react/packages/ui/src/Dashboard/TopIntegrations.css
  app/ui-react/packages/ui/src/Dashboard/TopIntegrationsCard.tsx
  app/ui-react/packages/ui/src/Shared/AggregatedMetricCard.tsx
  app/ui-react/packages/ui/src/index.css
  app/ui-react/packages/ui/stories/Shared/AggregatedMetricCard.stories.tsx
  app/ui-react/packages/ui/tests/AggregatedMetricCard.spec.tsx
  app/ui-react/packages/utils/src/dateHelpers.ts
  app/ui-react/syndesis/src/modules/dashboard/locales/dashboard-translations.en.json
  app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
Labels: approved

#269 Connection Card match previous styles, fix kebab
  app/ui-react/packages/ui/src/Connection/ConnectionCard.css
  app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx
Labels: approved

#267 chore: DRY the editor
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailSteps.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorSidebar.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorRoutes.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorSidebar.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/SelectActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/step/ConfigureStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/TemplateStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
  app/ui-react/syndesis/src/modules/integrations/components/index.ts
  app/ui-react/syndesis/src/modules/integrations/resolvers.ts
  app/ui-react/syndesis/src/modules/integrations/routes.ts
Labels: approved

#272 Recent Integrations & Top Integrations fix
  app/ui-react/packages/ui/src/Dashboard/Dashboard.tsx
  app/ui-react/packages/ui/src/Dashboard/RecentUpdatesItem.css
  app/ui-react/packages/ui/src/Dashboard/RecentUpdatesItem.tsx
  app/ui-react/packages/ui/src/Dashboard/TopIntegrations.css
  app/ui-react/packages/ui/src/Integration/IntegrationListItem.css
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx
Labels: approved

#275 fix: cut down on server fetching
  app/ui-react/packages/api/src/WithChangeListener.tsx
  app/ui-react/packages/api/src/WithConnections.tsx
  app/ui-react/packages/utils/src/debounce.ts
  app/ui-react/packages/utils/src/index.ts
  app/ui-react/syndesis/src/modules/integrations/pages/IntegrationsPage.tsx
Labels: approved

#273 feat: wire up linting support;
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/Integration/editor/steps/template/TemplateStepTemplateEditor.tsx
  app/ui-react/packages/ui/src/Shared/TextEditor.tsx
  app/ui-react/packages/utils/package.json
  app/ui-react/packages/utils/src/index.ts
  app/ui-react/packages/utils/src/lintHelpers.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/TemplateStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/WithTemplater.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/codemirror/abstract-language-lint.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/codemirror/freemarker-mode-lint.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/codemirror/index.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/codemirror/mustache-mode-lint.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/codemirror/template-symbol.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/codemirror/velocity-lint.ts
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/yarn.lock
Labels: approved

#277 Fix label height on Dashboard
  app/ui-react/packages/ui/src/Dashboard/TopIntegrations.css
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx
Labels: approved

#280 feat: connect file drag/drop support, misc alignments
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailBreadcrumb.tsx
  app/ui-react/packages/ui/src/Integration/editor/steps/template/TemplateStepTemplateEditor.tsx
  app/ui-react/packages/ui/src/Shared/DndFileChooser.tsx
  app/ui-react/packages/ui/src/Shared/WithDropzone.tsx
  app/ui-react/packages/ui/src/Shared/index.ts
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailHeader.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailSteps.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/WithTemplater.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/pages/detail/ActivityPageTable.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx
Labels: approved

#281 chore: set IDs on save/publish/cancel buttons to ease testing
  app/ui-react/packages/ui/src/Integration/IntegrationEditorLayout.tsx
Labels: approved

#284 feat: fetch the username and use it in the header
  app/ui-react/packages/api/src/WithUser.tsx
  app/ui-react/packages/api/src/index.ts
  app/ui-react/syndesis/src/app/App.tsx
  app/ui-react/syndesis/src/app/AppContext.tsx
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/app/__mocks__/App.tsx
Labels: approved

#282 fix: Set the right mix of headers for extension upload
  app/ui-react/packages/api/src/WithExtensionHelpers.tsx
  app/ui-react/packages/api/src/callFetch.ts
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionDetailsPage.tsx
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionImportPage.tsx
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionsPage.tsx
Labels: approved

#285 TTOOLS-596 Adds CreateView Wizard
  app/ui-react/packages/api/src/WithVirtualizationConnectionSchema.tsx
  app/ui-react/packages/api/src/WithVirtualizationHelpers.tsx
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListSkeleton.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewConfigurationForm.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewCreateLayout.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewCreateLayout.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewsImportLayout.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewsImportLayout.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationList.tsx
  app/ui-react/packages/ui/src/Data/index.ts
  app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ConnectionSchemaListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/SchemaNodeListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/ViewCreateApp.tsx
  app/ui-react/syndesis/src/modules/data/ViewsImportApp.tsx
  app/ui-react/syndesis/src/modules/data/index.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectSourcesPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/index.ts
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/index.ts
  app/ui-react/syndesis/src/modules/data/resolvers.ts
  app/ui-react/syndesis/src/modules/data/routes.ts
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewCreateSteps.tsx
  app/ui-react/syndesis/src/modules/data/shared/ViewsImportSteps.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
  app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
  app/ui-react/syndesis/src/modules/data/shared/index.ts
Labels: approved, status/review-requested

#289 feat: wire up publish button and update routing
  app/ui-react/packages/api/src/WithServerEvents.tsx
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.tsx
Labels: approved

#262 Support page
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsListItemBasic.tsx
  app/ui-react/packages/ui/src/Integration/index.ts
  app/ui-react/packages/ui/src/Shared/HelpDropdown.tsx
  app/ui-react/packages/ui/src/Shared/PfDropdownItem.tsx
  app/ui-react/packages/ui/src/Support/DownloadDiagnostics.tsx
  app/ui-react/packages/ui/src/Support/SupportPageBody.tsx
  app/ui-react/packages/ui/src/Support/index.ts
  app/ui-react/packages/ui/src/index.css
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/modules/support/components/SelectiveIntegrationList.tsx
  app/ui-react/syndesis/src/modules/support/pages/SupportPage.tsx
Labels: approved, status/review-requested

#290 feat: re-fetch upon receiving connected message; clear error on read
  app/ui-react/packages/api/src/Fetch.tsx
  app/ui-react/packages/api/src/WithApiConnectors.tsx
  app/ui-react/packages/api/src/WithChangeListener.tsx
  app/ui-react/packages/api/src/WithConnections.tsx
  app/ui-react/packages/api/src/WithConnectors.tsx
  app/ui-react/packages/api/src/WithExtensionIntegrations.tsx
  app/ui-react/packages/api/src/WithExtensions.tsx
  app/ui-react/packages/api/src/WithIntegration.tsx
  app/ui-react/packages/api/src/WithIntegrations.tsx
  app/ui-react/packages/api/src/WithMonitoredIntegration.tsx
  app/ui-react/packages/api/src/WithMonitoredIntegrations.tsx
  app/ui-react/packages/api/src/WithServerEvents.tsx
Labels: approved

#291 Implement API client connector details page
  app/ui-react/packages/api/src/WithApiConnector.tsx
  app/ui-react/packages/api/src/WithApiConnectorHelpers.tsx
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/ui/src/Customization/ApiConnectorDetail.tsx
  app/ui-react/packages/ui/src/Customization/ApiConnectorDetailCard.tsx
  app/ui-react/packages/ui/src/Customization/ApiConnectorDetailsForm.css
  app/ui-react/packages/ui/src/Customization/ApiConnectorDetailsForm.tsx
  app/ui-react/packages/ui/src/Customization/ApiConnectorInfo.tsx
  app/ui-react/packages/ui/src/Customization/ApiConnectorListItem.tsx
  app/ui-react/packages/ui/src/Customization/ApiConnectorReview.css
  app/ui-react/packages/ui/src/Customization/ApiConnectorReview.tsx
  app/ui-react/packages/ui/src/Customization/index.ts
  app/ui-react/packages/ui/stories/Customization/ApiConnectorDetail.stories.tsx
  app/ui-react/packages/ui/stories/Customization/ApiConnectorDetailsForm.stories.tsx
  app/ui-react/packages/ui/stories/Customization/ApiConnectorListItem.stories.tsx
  app/ui-react/packages/ui/stories/Customization/ApiConnectorListView.stories.tsx
  app/ui-react/packages/ui/stories/Customization/ApiConnectorReview.stories.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/ApiConnectorInfo.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/index.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.it.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/resolvers.ts
  app/ui-react/syndesis/src/modules/apiClientConnectors/routes.ts
Labels: approved, status/review-requested

#295 Fix for integration list label height
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.css
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx
Labels: approved

#287 feat: add data mapper step configurator
  app/ui-react/packages/api/src/constants.ts
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/atlasmap-adapter/src/DataMapperAdapter.tsx
  app/ui-react/packages/atlasmap-adapter/tests/DataMapperAdapter.spec.tsx
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/packages/atlasmap-assembly/src/app/app.component.html
  app/ui-react/packages/atlasmap-assembly/src/app/app.component.ts
  app/ui-react/packages/atlasmap-assembly/src/app/app.module.ts
  app/ui-react/packages/atlasmap-assembly/src/app/data-mapper-host.component.ts
  app/ui-react/packages/atlasmap-assembly/src/environments/environment.prod.ts
  app/ui-react/packages/atlasmap-assembly/src/environments/environment.ts
  app/ui-react/packages/models/src/extra.d.ts
  app/ui-react/packages/ui/src/Integration/IntegrationEditorLayout.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationEditorStepsListItem.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationVerticalFlow.tsx
  app/ui-react/packages/ui/src/Layout/ButtonLink.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorRoutes.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorSidebar.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/DataMapperPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/utils.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
  app/ui-react/syndesis/src/modules/integrations/index.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/TestAtlasmapPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/index.ts
  app/ui-react/syndesis/src/modules/integrations/resolvers.ts
  app/ui-react/yarn.lock
Labels: approved, status/review-requested

#301 refactor(IVP): refactors width, scroll, toggle
  app/ui-react/packages/ui/src/Integration/IntegrationEditorLayout.css
  app/ui-react/packages/ui/src/Integration/IntegrationFlowStep.css
  app/ui-react/packages/ui/src/Integration/IntegrationFlowStepDetails.css
  app/ui-react/packages/ui/src/Integration/IntegrationVerticalFlow.css
  app/ui-react/packages/ui/src/Integration/IntegrationVerticalFlow.tsx
Labels: approved, status/review-requested

#300 chore(integration-list-view): clean up styles around integration list
  app/ui-react/packages/ui/src/Integration/Details/IntegrationActions.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.css
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx
  app/ui-react/packages/ui/src/index.css
Labels: approved, enhancement, status/review-requested

#292 feat: Implement the 'describe data' page
  app/ui-react/packages/api/src/WithSteps.tsx
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
  app/ui-react/packages/ui/src/Integration/editor/endpoint/DescribeDataShapeForm.tsx
  app/ui-react/packages/ui/src/Integration/editor/endpoint/index.ts
  app/ui-react/packages/ui/src/Integration/editor/index.ts
  app/ui-react/packages/ui/src/Integration/editor/steps/index.ts
  app/ui-react/packages/ui/src/Integration/editor/template/TemplateStepCard.tsx
  app/ui-react/packages/ui/src/Integration/editor/template/TemplateStepTemplateEditor.tsx
  app/ui-react/packages/ui/src/Integration/editor/template/TemplateStepTypeSelector.tsx
  app/ui-react/packages/ui/src/Integration/editor/template/index.ts
  app/ui-react/packages/utils/src/makeResolver.ts
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailNavBar.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorRoutes.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/DescribeDataShapePage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithDescribeDataShapeForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/makeEditorResolvers.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/WithTemplater.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
  app/ui-react/syndesis/src/modules/integrations/resolvers.ts
Labels: approved

#306 Implements API client connector icon upload
  app/ui-react/packages/api/src/WithApiConnectorHelpers.tsx
  app/ui-react/packages/ui/src/Customization/ApiConnectorDetailsForm.css
  app/ui-react/packages/ui/src/Customization/ApiConnectorDetailsForm.tsx
  app/ui-react/packages/ui/stories/Customization/ApiConnectorDetailsForm.stories.tsx
  app/ui-react/packages/ui/stories/Customization/ExtensionDetail.stories.tsx
  app/ui-react/packages/ui/stories/Customization/ExtensionImportReview.stories.tsx
  app/ui-react/packages/ui/stories/Customization/ExtensionListItem.stories.tsx
  app/ui-react/packages/ui/stories/Customization/ExtensionListView.stories.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/ApiConnectorInfo.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.it.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
Labels: approved, status/review-requested

#307 fix(integration): fix metrics and activity ui bugs in detail view
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivity.css
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.css
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx
  app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.css
  app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
Labels: approved, status/review-requested

#302 Delete Step in Integration Editor
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: approved

#303 feat: embed Apicurio
  app/ui-react/.gitignore
  app/ui-react/package.json
  app/ui-react/packages/apicurio-adapter/package.json
  app/ui-react/packages/apicurio-adapter/src/ApicurioAdapter.tsx
  app/ui-react/packages/apicurio-adapter/src/index.ts
  app/ui-react/packages/apicurio-adapter/tests/ApicurioAdapter.spec.tsx
  app/ui-react/packages/apicurio-adapter/tsconfig.json
  app/ui-react/packages/apicurio-adapter/tsconfig.test.json
  app/ui-react/packages/apicurio-adapter/tslint.json
  app/ui-react/packages/apicurio-assembly/.editorconfig
  app/ui-react/packages/apicurio-assembly/README.md
  app/ui-react/packages/apicurio-assembly/angular.json
  app/ui-react/packages/apicurio-assembly/e2e/protractor.conf.js
  app/ui-react/packages/apicurio-assembly/e2e/src/app.e2e-spec.ts
  app/ui-react/packages/apicurio-assembly/e2e/src/app.po.ts
  app/ui-react/packages/apicurio-assembly/e2e/tsconfig.e2e.json
  app/ui-react/packages/apicurio-assembly/package.json
  app/ui-react/packages/apicurio-assembly/src/app/WindowRef.ts
  app/ui-react/packages/apicurio-assembly/src/app/apicurio-host.component.ts
  app/ui-react/packages/apicurio-assembly/src/app/app.component.css
  app/ui-react/packages/apicurio-assembly/src/app/app.component.html
  app/ui-react/packages/apicurio-assembly/src/app/app.component.spec.ts__
  app/ui-react/packages/apicurio-assembly/src/app/app.component.ts
  app/ui-react/packages/apicurio-assembly/src/app/app.module.ts
  app/ui-react/packages/apicurio-assembly/src/assets/.gitkeep
  app/ui-react/packages/apicurio-assembly/src/browserslist
  app/ui-react/packages/apicurio-assembly/src/environments/environment.prod.ts
  app/ui-react/packages/apicurio-assembly/src/environments/environment.ts
  app/ui-react/packages/apicurio-assembly/src/favicon.ico
  app/ui-react/packages/apicurio-assembly/src/index.html
  app/ui-react/packages/apicurio-assembly/src/karma.conf.js
  app/ui-react/packages/apicurio-assembly/src/main.ts
  app/ui-react/packages/apicurio-assembly/src/polyfills.ts
  app/ui-react/packages/apicurio-assembly/src/styles.css
  app/ui-react/packages/apicurio-assembly/src/test.ts
  app/ui-react/packages/apicurio-assembly/src/tsconfig.app.json
  app/ui-react/packages/apicurio-assembly/src/tsconfig.editor.json
  app/ui-react/packages/apicurio-assembly/src/tslint.json
  app/ui-react/packages/apicurio-assembly/tsconfig.json
  app/ui-react/packages/apicurio-assembly/tslint.json
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/packages/atlasmap-assembly/src/app/app.component.html
  app/ui-react/packages/atlasmap-assembly/src/app/data-mapper-host.component.ts
  app/ui-react/syndesis/package.json
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/api-provider/UploadPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/makeEditorResolvers.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
  app/ui-react/syndesis/src/setupProxy.js
  app/ui-react/yarn.lock
Labels: approved, status/review-requested

#309 fix: wire up describe data saving and buttons
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/utils.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/DescribeDataShapePage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithDescribeDataShapeForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.tsx
Labels: approved

#312 fix(integrationeditor): various ui updates
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailHistoryListView.css
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailHistoryListView.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationFlowAddStep.css
  app/ui-react/packages/ui/src/Integration/IntegrationFlowAddStep.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationStepsHorizontalItem.css
Labels: approved, status/review-requested

#305 chore(pf4-styles): integration list styles, about modal, pf deps
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.css
  app/ui-react/packages/ui/src/Shared/AboutModal.tsx
  app/ui-react/packages/ui/src/index.css
  app/ui-react/packages/ui/stories/Layout/AppLayout.stories.tsx
  app/ui-react/packages/ui/stories/Shared/AboutModal.stories.tsx
  app/ui-react/syndesis/public/apple-touch-icon.png
  app/ui-react/syndesis/public/favicon-16x16.ico
  app/ui-react/syndesis/public/favicon-24x24.ico
  app/ui-react/syndesis/public/favicon-32x32.ico
  app/ui-react/syndesis/public/favicon-64x64.ico
  app/ui-react/syndesis/public/favicon.ico
  app/ui-react/syndesis/public/index.html
  app/ui-react/syndesis/public/safari-pinned-tab.svg
  app/ui-react/syndesis/src/app/App.test.tsx
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/shared/PageTitle.tsx
  app/ui-react/syndesis/src/shared/images/FuseOnlineLogo_White.svg
  app/ui-react/syndesis/src/shared/images/syn-favicon.ico
  app/ui-react/syndesis/src/shared/images/syndesis_logo_full_darkbkg.svg
  app/ui-react/yarn.lock
Labels: approved, enhancement, status/review-requested

#311 chore: increase the multi-select widget height
  app/ui-react/packages/auto-form/src/widgets/FormSelectComponent.tsx
Labels: approved

#310 fix: expose the isInitialValid property and set it appropriately in the editor, add some IDs
  app/ui-react/packages/auto-form/src/AutoForm.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationEditorForm.tsx
  app/ui-react/packages/ui/src/Integration/editor/endpoint/DescribeDataShapeForm.tsx
  app/ui-react/packages/ui/src/Shared/TextEditor.tsx
  app/ui-react/packages/utils/src/autoformHelpers.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
Labels: approved

#315 feat: update required field prompts for auto forms
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
  app/ui-react/packages/auto-form/src/AutoForm.tsx
  app/ui-react/packages/auto-form/src/FormBuilder.tsx
  app/ui-react/packages/auto-form/src/models.ts
  app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormInputComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormSelectComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormTextAreaComponent.tsx
  app/ui-react/packages/utils/src/autoformHelpers.ts
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/modules/connections/components/WithConnectorForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/settings/pages/OAuthAppsPage.tsx
Labels: approved

#317 fix: show error message when submitting an invalid form
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationEditorForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/NothingToConfigure.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
Labels: approved, status/review-requested

#318 feat: add navigating away confirmation when in the integration editor
  app/ui-react/syndesis/package.json
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/resolvers.ts
  app/ui-react/syndesis/src/shared/WithLeaveConfirmation.tsx
  app/ui-react/typings/allpro__react-router-pause/index.d.ts
  app/ui-react/typings/allpro__react-router-pause/package.json
  app/ui-react/yarn.lock
Labels: approved

#320 fix: fix loaders and random stuff
  .circleci/config.yml
  app/ui-react/packages/models/src/extra.d.ts
  app/ui-react/packages/ui/src/Connection/ConnectionSkeleton.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionsListView.tsx
  app/ui-react/packages/ui/src/Customization/ApiConnectorListSkeleton.tsx
  app/ui-react/packages/ui/src/Customization/ExtensionListSkeleton.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsListSkeleton.tsx
  app/ui-react/packages/ui/src/Layout/PageLoader.tsx
  app/ui-react/packages/ui/src/Layout/index.ts
  app/ui-react/packages/ui/src/index.css
  app/ui-react/syndesis/src/index.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/ConnectionDetailsPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionDetailsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationDetailNavBar.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/SelectActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/ActivityPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/MetricsPage.tsx
  app/ui-react/syndesis/src/modules/settings/pages/OAuthAppsPage.tsx
  app/ui-react/syndesis/src/modules/support/pages/SupportPage.tsx
Labels: approved, status/review-requested

#323 fix(support): left align expanded panel form
  app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppExpanderBody.tsx
Labels: approved, status/review-requested

#325 fix(connection): rework connection details UI
  app/ui-react/packages/auto-form/src/AutoForm.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionDetailsForm.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionDetailsHeader.css
  app/ui-react/packages/ui/src/Connection/ConnectionDetailsHeader.tsx
Labels: approved, status/review-requested

#326 fix(connection): update create connection wizard and details cards
  app/ui-react/packages/ui/src/Connection/ConnectionDetailsForm.tsx
  app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx
Labels: approved, status/review-requested

#327 chore(ux-edits): apply ux enhancements
  app/ui-react/packages/ui/src/Dashboard/UptimeMetric.tsx
  app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppHeader.tsx
  app/ui-react/packages/ui/src/Shared/CopyToClipboard.tsx
  app/ui-react/packages/ui/src/Shared/HelpDropdown.tsx
  app/ui-react/packages/ui/src/Shared/index.ts
  app/ui-react/packages/ui/src/index.css
  app/ui-react/syndesis/public/favicon-16x16.ico
  app/ui-react/syndesis/public/favicon-24x24.ico
  app/ui-react/syndesis/public/favicon-32x32.ico
  app/ui-react/syndesis/public/favicon-64x64.ico
  app/ui-react/syndesis/public/favicon.ico
  app/ui-react/syndesis/public/index.html
  app/ui-react/syndesis/src/modules/dashboard/pages/DashboardPage.tsx
Labels: approved, status/review-requested

#329 fix: address the data mapper page error when adding a map on newly created integrations
  app/ui-react/packages/auto-form/src/FormBuilder.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/DataMapperPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/utils.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
Labels: approved

#333 Ui react customizations ui cleanup
  app/ui-react/packages/ui/src/Connection/ConnectionDetailsHeader.css
  app/ui-react/packages/ui/src/Customization/ApiConnectorDetailsForm.css
  app/ui-react/packages/ui/src/Customization/ApiConnectorDetailsForm.tsx
  app/ui-react/packages/ui/src/Customization/ApiConnectorReview.css
  app/ui-react/packages/ui/src/Customization/ApiConnectorReview.tsx
  app/ui-react/packages/ui/src/Customization/ExtensionDetail.css
  app/ui-react/packages/ui/src/Customization/ExtensionDetail.tsx
  app/ui-react/packages/ui/src/Customization/ExtensionIntegrationsTable.tsx
  app/ui-react/packages/ui/src/Customization/ExtensionOverview.tsx
  app/ui-react/packages/ui/src/Customization/ExtensionSupports.tsx
  app/ui-react/packages/ui/src/index.css
Labels: approved, status/review-requested

#339 fix: tell the backend to send us more things
  app/ui-react/packages/api/src/WithApiConnectors.tsx
  app/ui-react/packages/api/src/WithConnections.tsx
  app/ui-react/packages/api/src/WithConnectors.tsx
  app/ui-react/packages/api/src/WithExtensions.tsx
  app/ui-react/packages/api/src/WithIntegrations.tsx
  app/ui-react/packages/api/src/WithOAuthApps.tsx
Labels: approved

#338 TTOOLS-597 Adds view edit page
  app/ui-react/packages/api/src/WithVdbModel.tsx
  app/ui-react/packages/api/src/WithVirtualizationHelpers.tsx
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewEditContent.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewEditContent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewEditHeader.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewEditHeader.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.tsx
  app/ui-react/packages/ui/src/Data/index.ts
  app/ui-react/packages/ui/stories/Data/Views/ViewEditContent.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewEditHeader.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/syndesis/src/modules/data/index.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/ViewEditPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/index.ts
  app/ui-react/syndesis/src/modules/data/resolvers.ts
  app/ui-react/syndesis/src/modules/data/routes.ts
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: status/review-requested

#341 fix(ui): small bugs on connections, cicd, and drag n drop ui
  app/ui-react/packages/ui/src/Connection/ConnectionCreatorLayout.tsx
  app/ui-react/packages/ui/src/Integration/CiCd/CiCdEditDialog.tsx
  app/ui-react/packages/ui/src/Shared/DndFileChooser.tsx
Labels: approved, status/review-requested

#342 TTOOLS-637 DV wizard layouts
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewCreateLayout.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewCreateLayout.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewsImportLayout.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewsImportLayout.tsx
Labels: approved, status/review-requested

#335 feat: add array and custom component support to auto-form
  app/ui-react/packages/api/src/WithFilterOptions.tsx
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/auto-form/src/AutoForm.tsx
  app/ui-react/packages/auto-form/src/FormBuilder.tsx
  app/ui-react/packages/auto-form/src/index.ts
  app/ui-react/packages/auto-form/src/models.ts
  app/ui-react/packages/auto-form/src/widgets/AutoFormHelpBlock.tsx
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormCheckboxComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormHiddenComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormInputComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormSelectComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormTextAreaComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/TextButton.css
  app/ui-react/packages/auto-form/src/widgets/TextButton.tsx
  app/ui-react/packages/auto-form/src/widgets/helpers.ts
  app/ui-react/packages/auto-form/src/widgets/index.ts
  app/ui-react/packages/auto-form/stories/KitchenSink.stories.tsx
  app/ui-react/packages/auto-form/stories/SimpleExamples.stories.tsx
  app/ui-react/packages/auto-form/tests/AutoForm.spec.tsx
  app/ui-react/packages/auto-form/tests/FormCheckboxComponent.spec.tsx
  app/ui-react/packages/auto-form/tests/FormInputComponent.spec.tsx
  app/ui-react/packages/auto-form/tests/FormSelectComponent.spec.tsx
  app/ui-react/packages/auto-form/tests/FormTextAreaComponent.spec.tsx
  app/ui-react/packages/ui/src/Integration/editor/index.ts
  app/ui-react/packages/ui/src/Integration/editor/ruleFilter/RuleFilterCard.tsx
  app/ui-react/packages/ui/src/Integration/editor/ruleFilter/index.ts
  app/ui-react/packages/utils/src/autoformHelpers.ts
  app/ui-react/syndesis/src/modules/connections/components/WithConnectorForm.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorRoutes.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/makeEditorResolvers.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/RuleFilterStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/WithRuleFilterForm.tsx
  app/ui-react/syndesis/src/modules/settings/pages/OAuthAppsPage.tsx
Labels: approved

#344 TTOOLS-636: Commented out functionality not included for the tech preview release.
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationNavBar.tsx
Labels: approved, status/review-requested

#330 308 conditional delete integration editor
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: approved

#332 feat(logout): allow users to logout
  app/ui-react/packages/api/src/WithUserHelpers.tsx
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/ui/src/Shared/PfDropdownItem.tsx
  app/ui-react/packages/ui/src/index.css
  app/ui-react/packages/ui/stories/Layout/AppLayout.stories.tsx
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/index.tsx
  app/ui-react/syndesis/src/setupProxy.js
Labels: approved, enhancement, status/review-requested

#347 fix: properly filter the displayed steps based on the current position
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: approved

#343 TTOOLS-616
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
Labels: approved, status/review-requested

#354 fix(listviewtoolbar): decrease left/right padding so it aligns with list view content
  app/ui-react/packages/ui/src/Shared/DndFileChooser.tsx
  app/ui-react/packages/ui/src/Shared/ListViewToolbar.css
  app/ui-react/packages/ui/src/Shared/ListViewToolbar.tsx
Labels: approved, status/review-requested

#359 fix: revert bogus changes, fixes #348
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
Labels: approved, status/review-requested

#358 chore: add an array story to auto-form, add some tweaks and guards too
  app/ui-react/packages/auto-form/src/AutoForm.tsx
  app/ui-react/packages/auto-form/src/FormBuilder.tsx
  app/ui-react/packages/auto-form/src/models.ts
  app/ui-react/packages/auto-form/src/utils.ts
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.css
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/TextButton.tsx
  app/ui-react/packages/auto-form/stories/Array.stories.tsx
  app/ui-react/packages/auto-form/stories/FormWrapper.tsx
  app/ui-react/packages/auto-form/stories/KitchenSink.stories.tsx
  app/ui-react/packages/auto-form/stories/SimpleExamples.stories.tsx
  app/ui-react/packages/auto-form/stories/StoryWrapper.tsx
  app/ui-react/packages/utils/src/autoformHelpers.ts
  app/ui-react/syndesis/src/modules/connections/components/WithConnectorForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/WithRuleFilterForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/settings/pages/OAuthAppsPage.tsx
Labels: approved

#363 fix: proper saving and publishing of an integration
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
  app/ui-react/syndesis/src/shared/WithLeaveConfirmation.tsx
Labels: approved

#364 fix: optional initialValue prop for auto-form
  app/ui-react/packages/auto-form/src/AutoForm.tsx
Labels: approved

#365 Add breadcrumb to every editor page
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/api/src/useApiProvider.tsx
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorLayout.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationSaveForm.tsx
  app/ui-react/packages/ui/src/Integration/OperationsDropdown.tsx
  app/ui-react/packages/ui/src/Layout/PfNavLink.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorBreadcrumb.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/OperationsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SelectConnectionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/EditSpecificationPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/ReviewActionsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/SelectMethodPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/SetInfoPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/DataMapperPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/DescribeDataShapePage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/SelectActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/makeEditorResolvers.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/RuleFilterStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/step/ConfigureStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/TemplateStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/resolvers.ts
Labels: approved, status/review-requested

#368 fix: bring the data mapper step back from vacation
  app/ui-react/packages/api/src/WithSteps.tsx
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/utils.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: approved

#371 fix: connection creation bugfixes
  app/ui-react/packages/ui/src/Connection/ConnectionCreatorLayout.tsx
  app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx
  app/ui-react/packages/ui/src/Layout/WizardSteps.tsx
  app/ui-react/packages/ui/src/index.css
  app/ui-react/syndesis/src/modules/connections/ConnectionsCreatorApp.tsx
  app/ui-react/syndesis/src/modules/connections/components/ConnectionCreatorBreadSteps.tsx
  app/ui-react/syndesis/src/modules/connections/components/ConnectionCreatorBreadcrumb.tsx
  app/ui-react/syndesis/src/modules/connections/components/WithConnectorForm.tsx
  app/ui-react/syndesis/src/modules/connections/components/index.ts
  app/ui-react/syndesis/src/modules/connections/locales/connections-translations.en.json
  app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/index.ts
  app/ui-react/syndesis/src/modules/connections/pages/index.ts
Labels: approved, status/review-requested

#366 API Editor UI Round II
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperationsItem.css
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperationsItem.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.css
  app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/ReviewActionsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: approved

#373 TTOOLS-627 Some display improvements, added name validation
  app/ui-react/packages/api/src/WithVirtualizationHelpers.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/ViewEditPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewsImport/SelectViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
Labels: approved, status/review-requested

#374 The connections list page's disabled 'delete' menu item no longer triggers a delete confirmation
  app/ui-react/packages/ui/src/Connection/ConnectionCard.css
  app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionDetailsForm.tsx
  app/ui-react/packages/ui/src/Shared/PfDropdownItem.tsx
  app/ui-react/packages/ui/stories/Connection/ConnectionDetailsForm.stories.tsx
Labels: approved, status/review-requested

#380 fix(integrationdetails): various ui fixes
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailEditableName.css
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailEditableName.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailHistoryListViewItem.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.css
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationStatusDetail.css
  app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
  app/ui-react/packages/ui/src/Shared/ProgressWithLink.css
  app/ui-react/packages/ui/src/Shared/ProgressWithLink.tsx
  app/ui-react/syndesis/src/modules/integrations/components/TagIntegrationDialogWrapper.css
  app/ui-react/syndesis/src/modules/integrations/components/TagIntegrationDialogWrapper.tsx
Labels: approved, status/review-requested

#379 feat: implement the conditional flow page
  app/ui-react/packages/api/src/WithSteps.tsx
  app/ui-react/packages/api/src/constants.ts
  app/ui-react/packages/auto-form/src/AutoForm.tsx
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
  app/ui-react/packages/ui/src/Integration/Editor/choice/ChoiceCardHeader.tsx
  app/ui-react/packages/ui/src/Integration/Editor/choice/ChoiceViewMode.tsx
  app/ui-react/packages/ui/src/Integration/Editor/choice/index.ts
  app/ui-react/packages/ui/src/Integration/Editor/index.ts
  app/ui-react/packages/ui/src/Integration/Editor/ruleFilter/RuleFilterCard.tsx
  app/ui-react/packages/ui/src/Integration/Editor/ruleFilter/index.ts
  app/ui-react/packages/ui/src/Integration/Editor/shared/EditorPageCard.tsx
  app/ui-react/packages/ui/src/Integration/Editor/shared/index.ts
  app/ui-react/packages/ui/src/Integration/Editor/template/index.ts
  app/ui-react/packages/ui/stories/Integration/Editor/steps/TemplateStep.stories.tsx
  app/ui-react/syndesis/public/icons/steps/choice.svg
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorRoutes.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/WithChoiceConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/interfaces.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/utils.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/makeEditorResolvers.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/RuleFilterStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/TemplateStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: approved

#375 feat: api connector creator wizard
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/api/src/useApiConnector.tsx
  app/ui-react/packages/api/src/useApiProvider.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorCreatorLayout.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorDetailsForm.css
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorDetailsForm.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/index.ts
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/index.ts
  app/ui-react/packages/ui/src/Layout/AppBreadcrumb.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx
  app/ui-react/packages/ui/stories/Customization/ApiConnectorDetailsForm.stories.tsx
  app/ui-react/syndesis/src/i18n/locales/shared-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/ApiConnectorCreatorApp.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/ApiConnectorCreatorBreadcrumb.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/ApiConnectorCreatorWizardSteps.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/ApiConnectorInfo.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/ApiConnectorInfoForm.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/components/index.ts
  app/ui-react/syndesis/src/modules/apiClientConnectors/index.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/ApiConnectorDetailsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/DetailsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/EditSpecificationPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SelectMethodPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/resolvers.ts
  app/ui-react/syndesis/src/modules/apiClientConnectors/routes.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/ReviewActionsPage.tsx
Labels: approved

#383 fix: make sure that onClick event handlers are fired only once
  app/ui-react/packages/ui/src/Layout/ButtonLink.tsx
Labels: approved, status/review-requested

#387 TTOOLS-646 added save button enablement logic and exposed validation …
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewEditContent.tsx
  app/ui-react/syndesis/src/modules/data/pages/ViewEditPage.tsx
Labels: approved, status/review-requested

#388 TTOOLS-626 Added Cancel button to create virtualization page
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationCreatePage.tsx
Labels: approved, status/review-requested
