Repository syndesisio/syndesis-react, pull requests merged in 2019-06, with the labels that each got.

#386 fix: make defaultValue work again
  app/ui-react/packages/auto-form/src/utils.ts
Labels: approved

#389 TTOOLS-648 Improvements to wizards and virtualization publishing
  app/ui-react/packages/ui/src/Data/DvConnection/DvConnectionsListView.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewList.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Views/ViewList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationViewsPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/ConnectionSchemaContent.tsx
  app/ui-react/syndesis/src/modules/data/shared/DvConnectionsWithToolbar.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: approved

#390 fix: some i18n error
  app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/DetailsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/EditSpecificationPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/ReviewActionsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
  app/ui-react/syndesis/src/modules/connections/components/WithConnectorForm.tsx
  app/ui-react/syndesis/src/modules/connections/locales/connections-translations.en.json
  app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
  app/ui-react/syndesis/src/modules/data/pages/viewCreate/SelectNamePage.tsx
  app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/WithChoiceConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/WithRuleFilterForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: approved, status/review-requested

#391 fix: show the right steps in the editor
  app/ui-react/packages/api/src/WithSteps.tsx
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorForm.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationSaveForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/SaveIntegrationPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/DataMapperPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/ruleFilter/WithRuleFilterForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: approved, status/review-requested

#392 fix(integration): increase uptime metric text size
  app/ui-react/packages/ui/src/Dashboard/UptimeMetric.css
  app/ui-react/packages/ui/src/Dashboard/UptimeMetric.tsx
  app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.css
  app/ui-react/packages/ui/src/Integration/Metrics/IntegrationDetailMetrics.tsx
Labels: approved, status/review-requested

#393 chore: use the new staging env for preview links
  app/ui-react/syndesis/config.staging.json
Labels: approved

#404 fix: hide hidden fields and consider them not required for validation purposes
  app/ui-react/packages/auto-form/src/utils.ts
  app/ui-react/packages/utils/src/autoformHelpers.ts
Labels: approved, status/review-requested

#357 chore(styling): improve styling based on ux feedback
  app/ui-react/packages/auto-form/src/widgets/FormDurationComponent.tsx
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/Dashboard/RecentUpdatesItem.css
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailEditableName.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.css
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationStatus.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationVerticalFlow.css
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.css
  app/ui-react/packages/ui/src/Layout/AppLayout.tsx
  app/ui-react/packages/ui/src/Layout/AppTopMenu.tsx
  app/ui-react/packages/ui/src/Settings/OAuth/OAuthAppHeader.tsx
  app/ui-react/packages/ui/src/Shared/CopyToClipboard.tsx
  app/ui-react/packages/ui/src/Shared/HelpDropdown.tsx
  app/ui-react/packages/ui/src/Support/DownloadDiagnostics.tsx
  app/ui-react/packages/ui/src/index.css
  app/ui-react/packages/ui/stories/Layout/AppLayout.stories.tsx
  app/ui-react/packages/ui/tests/AppLayout.spec.tsx
  app/ui-react/syndesis/public/index.html
  app/ui-react/syndesis/public/red-hat-safari-pinned-tab.svg
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/images.d.ts
  app/ui-react/syndesis/src/shared/images/favicon.ico
  app/ui-react/syndesis/src/shared/images/img_avatar.svg
  app/ui-react/syndesis/src/shared/images/red-hat-apple-touch-icon.png
  app/ui-react/syndesis/src/shared/images/red-hat-brand-logo.png
  app/ui-react/syndesis/src/shared/images/red-hat-fuse-online-logo.png
  app/ui-react/syndesis/src/shared/images/red-hat-safari-pinned-tab.svg
  app/ui-react/syndesis/src/shared/images/syn-apple-touch-icon.png
  app/ui-react/syndesis/src/shared/images/syn-safari-pinned-tab.svg
  app/ui-react/typings/patternfly-react/index.d.ts
  app/ui-react/yarn.lock
Labels: approved, enhancement

#406 fix: broken step configuration
  app/ui-react/syndesis/src/modules/integrations/components/editor/step/WithConfigurationForm.tsx
Labels: approved, status/review-requested

#407 fix: sanitize the integration object before saving
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/api/src/useIntegrationHelpers.tsx
Labels: approved

#403 fix(ui): integration details, api connector upload
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.css
  app/ui-react/packages/ui/src/Integration/Activity/IntegrationDetailActivityItem.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.css
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.tsx
Labels: approved, status/review-requested

#384 API client connector wizard additional work
  app/ui-react/packages/api/src/useApiConnector.tsx
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/locales/api-client-connectors-translations.en.json
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/DetailsPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/pages/create/SecurityPage.tsx
  app/ui-react/syndesis/src/modules/apiClientConnectors/resolvers.ts
Labels: approved, status/review-requested

#405 chore(ux): apply followup ux feedback
  app/ui-react/packages/ui/src/Layout/AppLayout.tsx
  app/ui-react/packages/ui/src/Layout/AppTopMenu.tsx
  app/ui-react/packages/ui/src/Shared/HelpDropdown.tsx
  app/ui-react/packages/ui/tests/AppLayout.spec.tsx
Labels: approved, enhancement

#413 TTOOLS-624 improvements to DV wizard lists
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ConnectionSchemaListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/SchemaNodeListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewInfoListItem.tsx
Labels: approved

#402 feat: Implement conditional flows
  app/ui-react/packages/api/src/constants.ts
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/ui/src/Integration/ConditionsBackButtonItem.css
  app/ui-react/packages/ui/src/Integration/ConditionsBackButtonItem.tsx
  app/ui-react/packages/ui/src/Integration/ConditionsDropdown.tsx
  app/ui-react/packages/ui/src/Integration/ConditionsDropdownHeader.tsx
  app/ui-react/packages/ui/src/Integration/ConditionsDropdownItem.css
  app/ui-react/packages/ui/src/Integration/ConditionsDropdownItem.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorStepsListItem.css
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorStepsListItem.tsx
  app/ui-react/packages/ui/src/Integration/Editor/choice/ChoiceCardHeader.tsx
  app/ui-react/packages/ui/src/Integration/Editor/choice/ChoiceConfigurationView.tsx
  app/ui-react/packages/ui/src/Integration/Editor/choice/index.ts
  app/ui-react/packages/ui/src/Integration/index.ts
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorBreadcrumb.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepExpanderBody.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/WithChoiceConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/interfaces.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/utils.ts
Labels: approved, status/review-requested

#412 Test identifier work
  app/ui-react/packages/ui/src/Layout/AppTopMenu.tsx
  app/ui-react/packages/ui/src/Shared/AboutModalContent.tsx
  app/ui-react/packages/ui/stories/Layout/AppLayout.stories.tsx
  app/ui-react/packages/ui/stories/Shared/AboutModal.stories.tsx
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/app/locales/app-translations.en.json
  app/ui-react/syndesis/src/app/locales/app-translations.it.json
Labels: approved, status/review-requested

#421 Fix for escaped view names
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: approved

#414 fix(ui): various UI improvements
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorListItem.tsx
  app/ui-react/packages/ui/src/Customization/extensions/ExtensionImportCard.tsx
  app/ui-react/packages/ui/src/Customization/extensions/ExtensionListItem.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationActions.css
  app/ui-react/packages/ui/src/Integration/Details/IntegrationActions.tsx
  app/ui-react/packages/ui/src/Integration/Import/ImportPageUI.tsx
  app/ui-react/packages/ui/stories/Customization/ExtensionImportCard.stories.tsx
  app/ui-react/packages/ui/tests/Customization/ExtensionImportCard.spec.tsx
  app/ui-react/syndesis/src/modules/extensions/pages/ExtensionImportPage.tsx
Labels: approved, status/review-requested

#423 chore(ux): use appropriate icon for help dropdown
  app/ui-react/packages/ui/src/Layout/AppLayout.tsx
  app/ui-react/packages/ui/src/Shared/HelpDropdown.tsx
  app/ui-react/packages/ui/src/index.css
  app/ui-react/packages/ui/stories/Shared/HelpDropdown.stories.tsx
Labels: approved, enhancement, status/review-requested

#429 fix(ui): fix integration editor layout, wizard ui
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/ApiConnectorCreatorLayout.tsx
  app/ui-react/packages/ui/src/Customization/extensions/ExtensionImportReview.css
  app/ui-react/packages/ui/src/Customization/extensions/ExtensionImportReview.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorLayout.css
  app/ui-react/packages/ui/src/index.css
Labels: approved, status/review-requested

#430 Adds odata link to the virtualization list item
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: approved

#418 Fix for Integration Editor Action ListItem row
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorActionsListItem.tsx
Labels: approved

#433 feat: disallow nested conditional flow steps
  app/ui-react/packages/api/src/WithSteps.tsx
  app/ui-react/packages/models/src/extra.d.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: approved, status/review-requested

#434 Fixes for query client issues
  app/ui-react/packages/ui/src/Data/Virtualizations/SqlClientContent.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/SqlClientContent.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
  app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
Labels: approved

#435 Auto-validate for apiKey type
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
Labels: approved

#436 fix: Add syntax examples in condition help block
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: approved, status/review-requested

#437 fix: add the exposed URL if available to the detail page
  app/ui-react/packages/ui/src/Integration/Details/IntegrationExposedURL.tsx
  app/ui-react/packages/ui/src/Integration/Details/index.ts
  app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx
Labels: approved

#426 feat: oauth flow for connections
  app/ui-react/packages/api/src/WithConnectionHelpers.tsx
  app/ui-react/packages/api/src/callFetch.ts
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/api/src/useApiResource.tsx
  app/ui-react/packages/api/src/useConnectionHelpers.tsx
  app/ui-react/packages/api/src/useConnector.tsx
  app/ui-react/packages/api/src/useConnectorCredentials.tsx
  app/ui-react/packages/ui/src/Connection/ConnectorAuthorization.tsx
  app/ui-react/packages/ui/src/Connection/ConnectorConfigurationForm.tsx
  app/ui-react/packages/ui/src/Connection/index.ts
  app/ui-react/packages/utils/src/useRouteData.tsx
  app/ui-react/syndesis/public/oauth-redirect.html
  app/ui-react/syndesis/src/modules/connections/ConnectionsCreatorApp.tsx
  app/ui-react/syndesis/src/modules/connections/locales/connections-translations.en.json
  app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ConnectorsPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
  app/ui-react/syndesis/src/modules/connections/resolvers.ts
  app/ui-react/syndesis/src/modules/connections/routes.ts
Labels: approved, status/review-requested

#439 chore: Data Mapper should skip maven classpath resolution in Syndesis…
  app/ui-react/packages/atlasmap-assembly/src/app/data-mapper-host.component.ts
  app/ui-react/packages/atlasmap-assembly/src/environments/environment.prod.ts
  app/ui-react/packages/atlasmap-assembly/src/environments/environment.ts
Labels: approved

#441 fix(integrationlist): fix list row item overlap
  app/ui-react/packages/ui/src/Dashboard/Dashboard.css
  app/ui-react/packages/ui/src/Dashboard/TopIntegrations.css
  app/ui-react/packages/ui/src/Dashboard/TopIntegrationsCard.tsx
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperationsItem.css
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.css
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx
  app/ui-react/packages/ui/src/Shared/ProgressWithLink.css
  app/ui-react/packages/ui/src/index.css
Labels: approved, status/review-requested

#442 TTOOLS-652 Virtualization publishing fixes
  app/ui-react/packages/models/src/dv.d.ts
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.css
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationListItem.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationPublishStatus.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationPublishStatusDetail.css
  app/ui-react/packages/ui/src/Data/Virtualizations/VirtualizationPublishStatusDetail.tsx
  app/ui-react/packages/ui/src/Data/Virtualizations/models.ts
  app/ui-react/packages/ui/src/Data/index.ts
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationList.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationListItem.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationPublishStatus.stories.tsx
  app/ui-react/packages/ui/stories/Data/Virtualizations/VirtualizationPublishStatusDetail.stories.tsx
  app/ui-react/syndesis/src/modules/data/locales/data-translations.en.json
  app/ui-react/syndesis/src/modules/data/locales/data-translations.it.json
  app/ui-react/syndesis/src/modules/data/pages/VirtualizationsPage.tsx
  app/ui-react/syndesis/src/modules/data/shared/VirtualizationUtils.ts
Labels: approved

#438 various conditional flow fixes
  app/ui-react/packages/api/src/constants.ts
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/ui/src/Integration/ConditionsDropdown.tsx
  app/ui-react/packages/ui/src/Integration/ConditionsDropdownBody.tsx
  app/ui-react/packages/ui/src/Integration/index.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorBreadcrumb.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
Labels: approved, status/review-requested

#431 fix(wiz-toggle): fix wizard toggle icon click-ability
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/Layout/AppLayout.tsx
  app/ui-react/packages/ui/src/Layout/WizardSteps.css
  app/ui-react/packages/ui/src/Layout/WizardSteps.tsx
  app/ui-react/packages/ui/src/Shared/HelpDropdown.tsx
  app/ui-react/packages/ui/stories/Shared/HelpDropdown.stories.tsx
  app/ui-react/yarn.lock
Labels: approved, enhancement, status/review-requested

#440 fix: don't reset OAuth client state
  app/ui-react/syndesis/public/oauth-redirect.html
  app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ReviewPage.tsx
  app/ui-react/syndesis/src/modules/connections/resolvers.ts
Labels: approved, status/review-requested

#443 fix: template step requires an output data shape to be selected
  app/ui-react/packages/api/src/WithSteps.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.tsx
Labels: approved

#445 fix(5273): Mustache errors showing wrong line number
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/codemirror/mustache-mode-lint.ts
Labels: approved

#424 Fixes an issue when deleting an integration from it's detail page
  app/ui-react/syndesis/src/modules/integrations/components/WithIntegrationActions.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/ActivityPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/DetailsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/pages/detail/MetricsPage.tsx
Labels: approved, status/review-requested

#444 feat: connection detail page for OAuth connections
  app/ui-react/packages/api/src/WithConnections.tsx
  app/ui-react/packages/api/src/helpers/connectionFunctions.ts
  app/ui-react/packages/api/src/index.ts
  app/ui-react/packages/api/src/useApiConnectorCreator.tsx
  app/ui-react/packages/api/src/useApiConnectorSummary.tsx
  app/ui-react/packages/api/src/useApiProvider.tsx
  app/ui-react/packages/api/src/useApiProviderIntegration.tsx
  app/ui-react/packages/api/src/useApiProviderSpecification.tsx
  app/ui-react/packages/api/src/useApiProviderSummary.tsx
  app/ui-react/packages/api/src/useApiResource.tsx
  app/ui-react/packages/api/src/useConnection.tsx
  app/ui-react/packages/api/src/useConnectorCredentials.tsx
  app/ui-react/packages/api/src/useConnectorCredentialsConnect.tsx
  app/ui-react/packages/api/src/useConnectorVerifier.tsx
  app/ui-react/packages/ui/src/Connection/ConnectionDetailsOauthCard.tsx
  app/ui-react/packages/ui/src/Connection/index.ts
  app/ui-react/syndesis/src/modules/connections/components/WithConnectorForm.tsx
  app/ui-react/syndesis/src/modules/connections/locales/connections-translations.en.json
  app/ui-react/syndesis/src/modules/connections/pages/ConnectionDetailsPage.tsx
  app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
  app/ui-react/syndesis/src/modules/connections/useOAuthFlow.ts
  app/ui-react/syndesis/src/modules/connections/utils.ts
  app/ui-react/yarn.lock
Labels: approved, status/review-requested

#448 fix: hook up the describe data link
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/IntegrationEditorStepAdder.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/AddStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/utils.ts
Labels: approved, status/review-requested

#451 fix: logout
  app/ui-react/packages/api/src/WithUserHelpers.tsx
  app/ui-react/syndesis/public/logout.html
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/setupProxy.js
Labels: approved

#447 TTOOLS-651 Clear query results on form change
  app/ui-react/syndesis/src/modules/data/shared/WithVirtualizationSqlClientForm.tsx
Labels: approved

#449 fix(ui): various fixes
  app/ui-react/packages/ui/src/Connection/ConnectionCard.css
  app/ui-react/packages/ui/src/Connection/ConnectionCard.tsx
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperationsItem.css
  app/ui-react/packages/ui/src/Integration/Editor/apiProvider/ApiProviderReviewOperationsItem.tsx
  app/ui-react/packages/ui/src/Shared/DndFileChooser.css
  app/ui-react/packages/ui/src/Shared/DndFileChooser.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiSelectMethod.css
  app/ui-react/packages/ui/src/index.css
Labels: approved, status/review-requested

#450 chore(ux): remove avatar and stopped status icon, truncate long titles
  app/ui-react/packages/ui/src/Dashboard/RecentUpdatesItem.css
  app/ui-react/packages/ui/src/Dashboard/RecentUpdatesItem.tsx
  app/ui-react/packages/ui/src/Integration/Details/IntegrationDetailInfo.tsx
  app/ui-react/packages/ui/src/Integration/IntegrationsListItem.css
  app/ui-react/packages/ui/src/Integration/IntegrationsListItemBasic.tsx
  app/ui-react/syndesis/src/app/UI.tsx
  app/ui-react/syndesis/src/modules/support/components/SelectiveIntegrationList.tsx
Labels: approved, enhancement, status/review-requested

#453 chore: Update to AtlasMap 1.40.0-beta1
  app/ui-react/packages/atlasmap-assembly/package.json
  app/ui-react/packages/atlasmap-assembly/src/app/data-mapper-host.component.ts
  app/ui-react/yarn.lock
Labels: approved

#452 defer registering the service worker until the app loads it's config
  app/ui-react/syndesis/src/app/App.tsx
  app/ui-react/syndesis/src/index.tsx
Labels: approved

#454 fix: codemirror bugs
  app/ui-react/packages/ui/package.json
  app/ui-react/packages/ui/src/Integration/Editor/template/TemplateStepTemplateEditor.tsx
  app/ui-react/packages/ui/src/Integration/Editor/template/TemplateStepTypeSelector.tsx
  app/ui-react/packages/ui/src/Shared/TextEditor.tsx
  app/ui-react/packages/ui/src/Shared/TextEditor/TextEditor.css
  app/ui-react/packages/ui/src/Shared/TextEditor/TextEditor.tsx
  app/ui-react/packages/ui/src/Shared/TextEditor/abstract-language-lint.ts
  app/ui-react/packages/ui/src/Shared/TextEditor/freemarker-mode-lint.ts
  app/ui-react/packages/ui/src/Shared/TextEditor/index.ts
  app/ui-react/packages/ui/src/Shared/TextEditor/mustache-mode-lint.ts
  app/ui-react/packages/ui/src/Shared/TextEditor/template-symbol.ts
  app/ui-react/packages/ui/src/Shared/TextEditor/velocity-lint.ts
  app/ui-react/packages/ui/stories/Integration/Editor/steps/TemplateStep.stories.tsx
  app/ui-react/packages/utils/package.json
  app/ui-react/packages/utils/src/index.ts
  app/ui-react/packages/utils/src/lintHelpers.ts
  app/ui-react/syndesis/package.json
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorRoutes.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/TemplateStepPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/WithTemplater.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/template/useTemplater.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
Labels: approved, status/review-requested

#457 auto form and conditional flow bug fixes
  app/ui-react/packages/api/src/WithSteps.tsx
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/packages/auto-form/package.json
  app/ui-react/packages/auto-form/src/utils.ts
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.css
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
  app/ui-react/packages/auto-form/src/widgets/TextButton.tsx
  app/ui-react/syndesis/src/app/App.css
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
Labels: approved, status/review-requested

#456 fix: api provider bugs
  app/ui-react/packages/api/src/useApiProviderSummary.tsx
  app/ui-react/packages/ui/src/Integration/Editor/IntegrationEditorLayout.tsx
  app/ui-react/packages/ui/src/Integration/OperationsDropdown.css
  app/ui-react/packages/ui/src/Integration/OperationsDropdown.tsx
  app/ui-react/packages/ui/src/Layout/Breadcrumb.tsx
  app/ui-react/packages/ui/src/Shared/OpenApiReviewActions.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationCreatorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/IntegrationEditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorBreadcrumb.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/apiProvider/ReviewActionsPage.tsx
  app/ui-react/syndesis/src/modules/integrations/locales/integrations-translations.en.json
  app/ui-react/syndesis/src/modules/integrations/resolvers.ts
Labels: approved, status/review-requested

#460 fix: ensure any configured properties get passed into the state
  app/ui-react/syndesis/src/modules/integrations/components/editor/EditorApp.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/DescribeDataShapePage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/WithConfigurationForm.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/interfaces.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/makeEditorResolvers.ts
Labels: approved

#458 refactor(oauth): prevent credentials POST for non-OAuth
  app/ui-react/syndesis/src/modules/connections/pages/create/ConfigurationPage.tsx
Labels: approved

#459 TT-598 View editor highlighting
  app/ui-react/packages/ui/src/Data/Virtualizations/Views/ViewEditContent.tsx
  app/ui-react/packages/ui/src/Shared/TextEditor/TextEditor.css
  app/ui-react/packages/ui/src/Shared/TextEditor/TextEditor.tsx
Labels: approved

#462 fix: clicking on the about link doesn't change the history anymore
  app/ui-react/packages/ui/src/Shared/HelpDropdown.tsx
Labels: approved

#461 fix: properly compute the initial validity state in the api connector security page
  app/ui-react/packages/ui/src/Customization/apiClientConnectors/create/ApiClientConnectorCreateSecurity.tsx
Labels: approved, status/review-requested

#463 fix: properly show the initial value for the form fields in all cases
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigureActionPage.tsx
  app/ui-react/syndesis/src/modules/integrations/components/editor/makeEditorResolvers.ts
Labels: approved, status/review-requested

#464 fix: better title for the action configuration page
  app/ui-react/syndesis/src/modules/integrations/components/editor/endpoint/ConfigurationForm.tsx
Labels: approved

#465 chore: disable the service worker
  app/ui-react/syndesis/src/app/App.tsx
  app/ui-react/syndesis/src/app/index.ts
  app/ui-react/syndesis/src/index.tsx
Labels: approved

#466 fix: make the logo link use the html5 history push
  app/ui-react/packages/ui/src/Layout/AppLayout.tsx
  app/ui-react/packages/ui/stories/Layout/AppLayout.stories.tsx
  app/ui-react/packages/ui/tests/AppLayout.spec.tsx
  app/ui-react/syndesis/src/app/UI.tsx
Labels: approved, status/review-requested

#469 fix: allow atlasmap viewport to scroll if needed
  app/ui-react/packages/atlasmap-assembly/src/app/app.component.css
  app/ui-react/syndesis/src/modules/integrations/components/editor/dataMapper/DataMapperPage.tsx
Labels: approved

#468 fix: moar careful initial value massaging for array entries
  app/ui-react/packages/auto-form/src/utils.ts
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.css
  app/ui-react/packages/auto-form/src/widgets/FormArrayComponent.tsx
Labels: approved, status/review-requested

#470 fix: apply the data shape of the conditional flow's step adapted data shape to each conditional flow
  app/ui-react/packages/api/src/helpers/integrationFunctions.ts
  app/ui-react/syndesis/src/modules/integrations/components/editor/choice/ChoiceStepPage.tsx
Labels: approved, status/review-requested

#471 re-enable datavirt for development by default
  app/ui-react/syndesis/config.minishift.json
  app/ui-react/syndesis/config.proxy.json
  app/ui-react/syndesis/config.staging.json
Labels: approved

#472 fix: undo really trivial styling issue that happened, nothing to see here honest
  app/ui-react/syndesis/src/index.tsx
Labels: approved

#473 Fixes syndesis/#5263, Changed create environment call to POST
  app/ui-react/packages/api/src/WithEnvironmentHelpers.tsx
Labels: approved
